### PR TITLE
Update categories for clarity 

### PR DESCRIPTION
**Pull request by Fox-Islam**

### CODE REVIEW

**Comment by Fox-Islam** [comment]
@omarkmu Hi! I just saw your changes and would be happy to merge them into the upstream if you're okay with that? Feel free to let me know if not, or if there are additional changes you would like to make in this PR 👍

**Comment by omarkmu** [comment]
@Fox-Islam Of course, that's fine! I was planning on making a PR today, you beat me to it 🙂

**Comment by Fox-Islam** [comment]
> @Fox-Islam Of course, that's fine! I was planning on making a PR today, you beat me to it 🙂

If you'd like I can delete this PR and you can open one up when you feel ready - this was just the only way I could find to send a message through GitHub 😭

**Comment by omarkmu** [comment]
Oh, no worries, this PR can stay open! I don't have many other changes that would fit into this PR, but I was considering these clarity changes yesterday:

- vocabularyGrade could have the aliases 'beginner', 'intermediate', and 'advanced' added to them (the API docs do say level1, level2, level3, but I think those are a bit less clear).
- The purpose of startNumberOfSyllables and endNumberOfSyllables might be clearer with "min" and "max" in their names, but that's up to personal choice.

I didn't think they were as pertinent as the other commits so I just made a note of them to see what you think. If they sound alright, I can commit the changes and push them before the merge.

**Comment by Fox-Islam** [comment]
> Oh, no worries, this PR can stay open! I don't have many other changes that would fit into this PR, but I was considering these clarity changes yesterday:
> 
> * vocabularyGrade could have the aliases 'beginner', 'intermediate', and 'advanced' added to them (the API docs do say level1, level2, level3, but I think those are a bit less clear).
> * The purpose of startNumberOfSyllables and endNumberOfSyllables might be clearer with "min" and "max" in their names, but that's up to personal choice.
> 
> I didn't think they were as pertinent as the other commits so I just made a note of them to see what you think. If they sound alright, I can commit the changes and push them before the merge.

Sure thing, both of those changes sound reasonable! 
I don't know what start/endNumberOfSyllables actually does, it was in the docs under "letter_s" and "letter_e" so I just took whatever description they had for it 😅

**Comment by omarkmu** [comment]
> Sure thing, both of those changes sound reasonable!
> I don't know what start/endNumberOfSyllables actually does, it was in the docs under "letter_s" and "letter_e" so I just took whatever description they had for it 😅

They correspond to the "number of syllables" option in the [advanced search](https://krdict.korean.go.kr/eng/dicSearchDetail/searchDetailWordsResult?nation=eng&nationCode=6); it limits the results to words with a certain number of syllables. Oddly enough, after checking just now, I noticed that when either of the two are omitted it doesn't function correctly... so if there's a min without a max, or vice versa, it seems to ignore the options.

Anyway, I'll go ahead and push those commits now!

**Comment by Fox-Islam** [comment]
> They correspond to the "number of syllables" option in the [advanced search](https://krdict.korean.go.kr/eng/dicSearchDetail/searchDetailWordsResult?nation=eng&nationCode=6); it limits the results to words with a certain number of syllables. Oddly enough, after checking just now, I noticed that when either of the two are omitted it doesn't function correctly... so if there's a min without a max, or vice versa, it seems to ignore the options.
> 
> Anyway, I'll go ahead and push those commits now!

Thank you! I'm just preparing the change to the wiki, I'll merge once I've got that ready :)

**Pull request merged**
